export const STORE_SERVICE = "STORE_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE"

export const SAVE_BOOKING_INFO = "SAVE_BOOKING_INFO";

export const GET_PRICE_SUCCESS = "GET_PRICE_SUCCESS";
export const GET_PRICE_FAIL = "GET_PRICE_FAIL";
export const GET_PRICE_REQUEST = "GET_PRICE_REQUEST";